
title: 'glbinding'
author: 'CG Internals, Potsdam, Germany'

google_font_sans_serif: 'Source+Sans+Pro:600,300'
google_font_monospace: 'Source+Code+Pro:400'

# Handling Reading
safe: true
encoding: utf-8

documentations:
  - master
  - v2.1
  - v2.0
  - v1.1
  - v1.0

documentation_states:
  master: info
  v2.1: success
  v2.0: warning
  v1.1: danger
  v1.0: danger

markdown: kramdown
highlighter: rouge
kramdown:
  hard_wrap: false
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

include: [ "*.html" ]

sass:
  style: compressed
